language: ruby
rvm:
- 2.1.0
- 2.2.0
- 2.3.4
script: rake test
notifications:
  slack:
    secure: KHNfsi7Y+cJ93zXFwYGBF1Ths87c6ipiVZvIMPpE4MfAtniAo9Qu/upeh4MD2P/iKwwmSm4skiztyGiOJOur5VEVjUBPKmxjQrt67tSs+KC15MFmEKuEL0C0BSMscYVrs1eTbFGdp6dRxEquS4WJ78IxySwmCTHFNZXVx2Jvvb290VZ7IuqS7gQV+UEDpGn0rrc+fYiZS6LN85lJh8ngU7J12thyIk2DYb2RKIBzeWcxxxU1i5L8mLRH3T0IKn/3p8E+NBnNVTJPuFdg/jz5n8Rux/a0IlFeUZfVa7TerTT8djfGVWVurAJrNWOdZfE5M2Yn6HSvoRBqUfnvvWgincNf04m8EZcJNJghPMoe6IKDckgHJryAYDzBVV7lZbr/0GEAsJIM6mU6Zc7uFfhUBZND9OBKY+Hjz5L9xg0FBMyXy3rWIN/t3fpNpEswTjMnz8Qzrtq0lDsMf8im6VrW46Sm79LZHEg4O9+WyH+QL/VQsGffPWCp5aiCigxcuJB3ExNJXDiyDA5wrawxKHnHEwPeKqKE6lScUBmeOwJIbMXyzfh6Nf7mJItwv+EhD3cTd7b84XQONkfKnkvILD29JM441gAOotCOCDAAysgSGlBLMWM5ZaUWiO0N7bUJFcVr2U0SITNGo++ZhMnP/xEWA+pQNkTAVCHg/I5ePCBJsFk=
